from agents.base_agent import BaseAgent
from agents.state import RecruitmentState
from config.log_config import AppLogger

logger = AppLogger(__name__)


class ApproverAgent(BaseAgent):
    def __init__(self, llm):
        self.llm = llm

    def run(self, state: RecruitmentState) -> RecruitmentState:
        if state.stop_pipeline:
            logger.info("[ApproverAgent] Pipeline stopped. Skipping approval.")
            return state

        if not state.matched_jd:
            logger.warn("[ApproverAgent] No matched JD found. Skipping approval.")
            state.approved_candidate = None
            return state

        if not state.parsed_cv:
            logger.warn("[ApproverAgent] No parsed CV found. Cannot approve.")
            state.approved_candidate = None
            return state

        logger.info("[ApproverAgent] Candidate approved without re-verification.")
        state.approved_candidate = state.parsed_cv

        # LLM-based CV Summary
        try:
            prompt = (
                "You are a high school admissions officer. Based on the student's profile below, write a short summary **in Vietnamese** "
                "to describe their academic strengths and potential.\n\n"
                "Your summary (in Vietnamese) should include:\n"
                "- Highlighted subject scores\n"
                "- Academic achievements such as awards, competitions, or scholarships\n"
                "- Thinking ability, self-learning or learning motivation (if mentioned)\n"
                "- How well the student fits the specialized class (e.g., Math major)\n\n"
                f"Student Profile:\n{state.parsed_cv}\n\n"
                "Return only 3–5 sentences in natural Vietnamese. Do not explain anything. No formatting, no bullet points."
            )

            raw_response = self.llm.invoke(prompt)
            # Safely extract string content
            if isinstance(raw_response, dict):
                content = raw_response.get("data", "")
            elif hasattr(raw_response, "json"):
                try:
                    content = raw_response.json().get("data", "")
                except Exception:
                    content = getattr(raw_response, "text", str(raw_response))
            elif hasattr(raw_response, "content"):
                content = raw_response.content
            elif isinstance(raw_response, (str, bytes)):
                content = raw_response
            else:
                content = str(raw_response)

            # Decode bytes if needed
            if isinstance(content, bytes):
                content = content.decode("utf-8")

            content = content.strip()
            if not content:
                raise ValueError("Received empty response from LLM.")

            # Remove Markdown block formatting (``` or ```json)
            if content.startswith("```"):
                content = content.strip().strip("`")
                if content.lower().startswith("json"):
                    content = content[4:].strip()

            state.cv_summary = content
            logger.info("[ApproverAgent] CV summary generated by LLM.")
            logger.debug(f"[ApproverAgent] state.cv_summary:\n{state.cv_summary}")

        except Exception as e:
            logger.error(f"[ApproverAgent] Failed to summarize CV: {e}")
            state.cv_summary = None

        return state
